# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from PyQt5 import QtCore, QtWidgets

import frame


class UiForm(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(412, 220)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 411, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 301, 31))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 142, 75, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(140, 180, 271, 20))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 40, 391, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.go)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit, self.lineEdit_2)
        Form.setTabOrder(self.lineEdit_2, self.pushButton)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("Form", "CleanWechatFiles GUI By Joinsodome [版本 0.1]"))
        self.label.setText(_translate("Form", "           CleanWechatFiles GUI By Joinsodome [版本 0.1]"))
        self.label_2.setText(_translate("Form", "将以上的所有信息填完，点击GO，即可开始畅快的清理！"))
        self.pushButton.setText(_translate("Form", "GO!"))
        self.label_3.setText(_translate("Form", "Plagiarism is strictly prohibited.严禁抄袭。"))
        self.label_4.setText(_translate("Form", "请输入您的Wechat Files路径（在微信->设置->通用设置中）："))
        self.label_5.setText(_translate("Form", "请输入备份的zip路径（包括zip文件名）："))

    def go(self):
        docpath = self.lineEdit.text()
        zip_here = self.lineEdit_2.text()
        if not docpath or not zip_here:
            QtWidgets.QMessageBox.warning(self, '警告 - CleanWechatFiles GUI', '两个输入框不准为空！')
        else:
            frame_ = frame.Framework(docpath, zip_here)
            QtWidgets.QMessageBox.about(self, '提示 - CleanWechatFiles GUI', '已启动框架！这个过程比较复杂，心焦了可以看日志目录~')
            try:
                frame_.run()
            except Exception as e:
                print(e)
                QtWidgets.QMessageBox.critical(self, '错误 - CleanWechatFiles GUI', '发生不可抗拒错误，具体情况可看日志！')
            else:
                QtWidgets.QMessageBox.about(self, '提示 - CleanWechatFiles GUI', 'done~')


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    form = UiForm()
    form.show()
    sys.exit(app.exec_())
